### ISSUE TITLE
minQty error

### ISSUE THREAD

**Issue by Simazuba** [awallish/BinanceArbitrageBot#5]
Hello. Few weeks ago start getting this error:

Traceback (most recent call last):
  File "C:\Users\Tom\Desktop\awallish\arbitrageBot3.py", line 12, in <module>
    binance.initializeLotInfo()
  File "C:\Users\Tom\Desktop\awallish\binance.py", line 277, in initializeLotInfo
    lots[lot]['digits'] = numAfterPoint(decimal.Decimal(lots[lot]['minQty']).normalize())
KeyError: 'minQty'

Could you help to fix this problem?

**Comment by B9daz** [comment]
I have the same error, any solution?

**Comment by cyberjunky** [comment]
@B9daz @redfly111 a quick hack, change this line in binance.py:

```
def initializeLotInfo():
...
        lots[key['baseAsset']] = key['filters'][1]
```
to:
```
        lots[key['baseAsset']] = key['filters'][2]
```
No warranties... keep me posted on experiences and results as reward!
